name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - GroupC
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
    - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What email address is best to get in touch should we require more information?
      placeholder: email@example.com
    validations:
      required: false
  - type: textarea
    id: user-description
    attributes:
      label: Describe the bug
      description: Explain in as much detail as possible to help us understand the severity of this bug
      placeholder: Describe the bug here!
    validations:
      required: true
  - type: dropdown
    id: user-version
    attributes:
      label: Version
      description: Tell us what version of our application you were running
      options:
        - 0.1-alpha-1 (Pre-release v1.0)
        - 0.1-alpha-2 (Pre-release v2.0)
        - 0.1-alpha-3 (Pre-release v3.0)
        - 0.1-alpha-4 (Pre-release v4.0)
        - 0.1-alpha-5 (Pre-release v5.0)
    validations:
      required: true
  - type: textarea
    id: user-extra
    attributes:
      label: Any additional information?
      description: Let us know anything else you wish to tell us about the bug such as how to recreate it or important points surrounding the effects of the bug
      placeholder: Add extra information here!
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/cammybisset/Group-C-Repository/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
